apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: port-cluster
  namespace: config-control
spec:
  description: An autopilot cluster.
  enableAutopilot: true
  location: europe-west1
  releaseChannel:
    channel: REGULAR
  networkRef:
    name: port-cluster
  subnetworkRef:
    external: port-cluster
