apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jetstack-paul
    config.kubernetes.io/depends-on: container.cnrm.cloud.google.com/namespaces/config-control/ContainerCluster/port-cluster
  name: port-cluster
  namespace: config-control
spec:
  location: global
  authority:
    issuer: https://container.googleapis.com/v1/projects/jetstack-paul/locations/europe-west1/clusters/port-cluster
  endpoint:
    gkeCluster:
      resourceRef:
        name: port-cluster
