apiVersion: configsync.gke.io/v1beta1
kind: RootSync
metadata:
  name: cis-gke-v1-5-0
  namespace: config-management-system
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/GoogleCloudPlatform/gke-policy-library
    branch: main
    dir: "anthos-bundles/cis-gke-v1.5.0"
    auth: none
