---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
        args:
          - --args=-write=true
          - --args=-recursive
      - id: terraform_validate
      - id: terraform_providers_lock
        args:
          - --hook-config=--mode=always-regenerate-lockfile
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.21.0  # or higher tag
    hooks:
      - id: yamllint
        exclude: ^charts/
        args: [-c, .yamllint.yaml, --format, parsable]
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2  # or other specific tag
    hooks:
      - id: yamlfmt
        exclude: ^charts/
        args: [--mapping, '2', --sequence, '4', --offset, '2', --width, '150']
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.28.5
    hooks:
      - id: check-github-workflows
        args: [--verbose]
