apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: replaceme
  namespace: config-control
spec:
  description: An autopilot cluster.
  enableAutopilot: true
  location: us-west1
  releaseChannel:
    channel: REGULAR
  networkRef:
    name: replaceme
  subnetworkRef:
    external: replaceme