apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: gkehubfeaturemembership-acm-dev
  namespace: config-control
  annotations:
    config.kubernetes.io/depends-on: gkehub.cnrm.cloud.google.com/namespaces/config-control/GKEHubMembership/gkehubmembership-dev
spec:
  projectRef:
    external: jetstack-paul
  location: global
  membershipRef:
    name: gkehubmembership-dev
  featureRef:
    name: gkehubfeature-acm
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        syncRepo: "https://github.com/GoogleCloudPlatform/gke-policy-library/tree/main"
        syncBranch: "main"
        policyDir: "bundles/cis-k8s-v1.5.1"
        syncWaitSecs: "20"
        syncRev: "HEAD"
    policyController:
      enabled: true
      exemptableNamespaces:
        - "kube-system"
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
      auditIntervalSeconds: "20"
    hierarchyController:
      enabled: false
