---
# Source: gke-autopilot/templates/computenetwork.yaml
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeNetwork
metadata:
  name: my-cluster
  namespace: config-control
spec:
  routingMode: REGIONAL
  autoCreateSubnetworks: true
---
# Source: gke-autopilot/templates/containercluster.yaml
apiVersion: container.cnrm.cloud.google.com/v1beta1
kind: ContainerCluster
metadata:
  name: my-cluster
  namespace: config-control
spec:
  description: An autopilot cluster.
  enableAutopilot: true
  location: europe-west1
  releaseChannel:
    channel: REGULAR
  networkRef:
    name: my-cluster
  subnetworkRef:
    external: my-cluster
---
# Source: gke-autopilot/templates/gkehubfeaturemembership.yaml
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubFeatureMembership
metadata:
  name: my-cluster
  namespace: config-control
  annotations:
    config.kubernetes.io/depends-on: gkehub.cnrm.cloud.google.com/namespaces/config-control/GKEHubMembership/my-cluster
spec:
  projectRef:
    external: jetstack-paul
  location: global
  membershipRef:
    name: my-cluster
  featureRef:
    name: gkehubfeature-acm
  configmanagement:
    configSync:
      sourceFormat: unstructured
      git:
        syncRepo: https://github.com/paulwilljones/gke-enterprise-self-service
        syncBranch: main
        policyDir: root-syncs
        syncWaitSecs: '20'
        syncRev: HEAD
        secretType: none
    policyController:
      enabled: true
      exemptableNamespaces:
        - kube-system
      referentialRulesEnabled: true
      logDeniesEnabled: true
      templateLibraryInstalled: true
      auditIntervalSeconds: '20'
    hierarchyController:
      enabled: false
---
# Source: gke-autopilot/templates/gkehubmembership.yaml
apiVersion: gkehub.cnrm.cloud.google.com/v1beta1
kind: GKEHubMembership
metadata:
  annotations:
    cnrm.cloud.google.com/project-id: jetstack-paul
    config.kubernetes.io/depends-on: container.cnrm.cloud.google.com/namespaces/config-control/ContainerCluster/my-cluster
  name: my-cluster
  namespace: config-control
spec:
  location: global
  authority:
    issuer: https://container.googleapis.com/v1/projects/jetstack-paul/locations/europe-west1/clusters/my-cluster
  endpoint:
    gkeCluster:
      resourceRef:
        name: my-cluster
