name: 'Add ContainerCluster manifest'
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Name of the GKE cluster
      location:
        type: string
        description: Location of GKE cluster
      instance_type:
        type: string
        description: Type of GKE cluster (Autopilot|Standard)
      port_context:
        required: false
        description:
          Who triggered the action and general context (blueprint, run id, etc...)
        type: string
jobs:
  Add-ContainerCluster:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - run: |
            mkdir user-clusters/${{ inputs.name }}
            cp bases/gke-autopilot/* user-clusters/${{ inputs.name }}/
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.metadata.name = "${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/containercluster.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.spec.location = "${{ inputs.location }}"' 'user-clusters/${{ inputs.name }}/containercluster.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.spec.networkRef.name = "${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/containercluster.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.spec.subnetworkRef.external = "${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/containercluster.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.metadata.name = "${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/computenetwork.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.metadata.name = "${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/gkehubmembership.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.metadata.annotations."config.kubernetes.io/depends-on" = "container.cnrm.cloud.google.com/namespaces/config-control/ContainerCluster/${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/gkehubmembership.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.spec.authority.issuer = "https://container.googleapis.com/v1/projects/jetstack-paul/locations/${{ inputs.location }}/clusters/${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/gkehubmembership.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.spec.endpoint.gkeCluster.resourceRef.name = "${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/gkehubmembership.yaml'

        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.metadata.name = "${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/gkehubfeaturemembership.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.metadata.annotations."config.kubernetes.io/depends-on" = "gkehub.cnrm.cloud.google.com/namespaces/config-control/GKEHubMembership/${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/gkehubfeaturemembership.yaml'
        - uses: mikefarah/yq@master
          with:
            cmd: yq -i '.spec.membershipRef.name = "${{ inputs.name }}"' 'user-clusters/${{ inputs.name }}/gkehubfeaturemembership.yaml'

        - name: Create Pull Request
          uses: peter-evans/create-pull-request@v6
          with:
            commit-message: add ${{ inputs.name }} GKE cluster in ${{ inputs.location }}
            title: Add ${{ inputs.name }} GKE cluster
            branch: add-gke-${{ inputs.name }}
            delete-branch: true
            add-paths: user-clusters/${{ inputs.name }}
