---
name: Delete ContainerCluster manifest
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        description: Name of the GKE cluster
      location:
        type: string
        description: Location of GKE cluster
      port_context:
        required: false
        description: Who triggered the action and general context (blueprint, run id, etc...)
        type: string
jobs:
  Delete-ContainerCluster:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          rm -rf user-clusters/${{ inputs.name }}/${{ inputs.location }}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: delete ${{ inputs.name }} GKE cluster in ${{ inputs.location }}
          title: Delete ${{ inputs.name }} GKE cluster
          branch: rm-gke-${{ inputs.name }}
          delete-branch: true
          add-paths: user-clusters/${{ inputs.name }}/${{ inputs.location }}
