name: 'GKE Config Controller'
on:
  workflow_dispatch:
jobs:
  Config-Controller:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: 'actions/checkout@v4'
      - uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'jetstack-paul'
          workload_identity_provider: 'projects/993897508389/locations/global/workloadIdentityPools/github/providers/my-repo'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
